/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;
import java.util.Random;
import java.util.ArrayList;
public class App {

    public static  ArrayList<Integer> roll (int num){

        ArrayList<Integer> arr = new ArrayList<Integer>();
        Random random = new Random();
        int rand = 0;
        for(int i =0;i<num;i++){
            while (true){
                rand = random.nextInt(7);
                if(rand !=0) break;
            }
            arr.add(rand);
//   System.out.println(rand);
        }


        return arr;
    }

    public static boolean containsDuplicates(int[] arr){
        boolean val =false ;
        for(int i=0;i<arr.length;i++){
            for(int j = i + 1; j < arr.length; j++) {
                if(arr[i] == arr[j])
                {val = true ;
                    break;}
            }}
        return val;
    }
    public static double average(int []arr) {
        double sum = 0;
        double avg = 0;
        int count = 0;
        for(int i = 0;i<arr.length;i++){
            sum = sum + arr[i];
            count++;
        }

        return sum/count;
    }
    public static int lowestaverage(int [][]arr) {
        ArrayList<Integer> avgArr = new ArrayList<Integer>();
        int sum = 0;
        int avg = 0;
        int count = 0;
        for(int i = 0;i<arr.length;i++){
            for(int y =0 ;y<arr[i].length ;y++){
                sum = sum + arr[i][y];
                count++;
                avg = sum/arr[i].length;
            }
            avgArr.add(avg);
            // System.out.print(avgArr[i]);

            avg = 0;

        }
        int min = avgArr.get(0);
        for (int i = 1; i < avgArr.size(); i++) {
            if (avgArr.get(i) < min) {
                min = avgArr.get(i);
            }
        }
//        System.out.print(avgArr);
        return min;
    }
    public static void main(String[] args) {
        int []arr = {1,2,6,3,1};
        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };
        System.out.println(roll(4));
        System.out.println(containsDuplicates(arr));
        System.out.println(average(arr));
        System.out.println(	lowestaverage(weeklyMonthTemperatures));
    }
}
