/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary2;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    Library classUnderTest = new Library();
    @Test void someLibraryMethodReturnsTrue() {

        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
    @Test
    public void testroll() {
        int rollsNumber = 4;
        assertEquals(rollsNumber, classUnderTest.roll(rollsNumber).size());
    }
    @Test
    public void averageTest() {
        assertEquals(2.6, classUnderTest.average(new int[] {1,2,6,3,1}));
    }

    @Test
    public void containsDuplicates() {
        assertTrue(classUnderTest.containsDuplicates(new int[] {1,2,6,3,1}));
    }
    @Test
    public void lowestAverage() {
        assertArrayEquals(new int[] {55, 54, 60, 53, 59, 57, 61},
                classUnderTest.lowestAverage(new int[][] {
                        {66, 64, 58, 65, 71, 57, 60},
                        {57, 65, 65, 70, 72, 65, 51},
                        {55, 54, 60, 53, 59, 57, 61},
                        {65, 56, 55, 52, 55, 62, 57}
                }));
    }
}
